[package]
name    = "man"
version = "0.0.0"
authors = ["Casey Rodarmor <casey@rodarmor.com>"]
edition = "2018"
publish = false

[dependencies]
anyhow   = "1.0.28"
fehler   = "1.0.0"
tempfile = "3.1.0"
regex    = "1.3.6"
