[package]
name    = "changelog"
version = "0.0.0"
authors = ["Casey Rodarmor <casey@rodarmor.com>"]
edition = "2018"
publish = false

[dependencies]
anyhow       = "1.0.28"
cargo_toml   = "0.8.0"
chrono       = "0.4.11"
fehler       = "1.0.0"
git2         = "0.13.1"
serde_yaml   = "0.8.11"
structopt    = "0.3.12"
strum        = "0.18.0"
strum_macros = "0.18.0"

[dependencies.serde]
version  = "1.0.106"
features = ["derive"]

[dependencies.url]
version = "2.1.1"
features = ["serde"]
